#define PPDStart			0
#define PPDGeneral			1
#define PPDBasicCap			2
#define PPDPageSize			3
#define PPDPageRegion		4
#define PPDImageableArea	5
#define PPDPaperDimension	6
#define PPDConstraints		7
#define PPDLanguageFile1		8
#define PPDLanguageFile2		9
#define PPDLanguageFile3		10
#define PPDLanguageFile4		11

const bigtextchunk chunks[] =
{
"*PPD-Adobe: \"4.3\"\n"
"\n"
"*%%******************************************************************************\n"
"*%%\n"
"*%%   PPD file for Index Braille Embossers in use with the Common UNIX Printing\n"
"*%%   System (CUPS).\n"
"*%%\n"
"*%%	 Produced by Macula Datorkonsult for Index Braille AB (http://www.indexbraille.com).\n"
"*%%\n"
"*%%	 Copyright (c) 2005-2011 Index Braille AB.  All Rights Reserved.\n"
"*%%\n"
"*%%	 Generated by %s\n"
"*%%\n"
"*%%	 Revision History:\n"
"*%%	 Date       Vers   By     Comment\n"
"*%%	 2006-01-11	 1.0   AU     Inital Release\n"
"*%%	 2006-01-25	 1.01  AU     Added more paper sizes, corrected some dimensions\n"
"*%%	 2006-01-27	 1.02  AU     Added 1284DeviceID information\n"
"*%%	 2006-02-15	 1.03  AU     Removed German_bm.ibk due to Windows DLL dependency\n"
"*%%	 2006-04-03	 1.1   AU     Prepared for PDE use\n"
"*%%	 2006-05-16	 1.1.1 AU     Final touch for 1.1 delivery\n"
"*%%	 2011-05-20	 2.0.0 AU     Release 2.0a0\n"
"*%%\n"
"*%%******************************************************************************\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDGeneral] : General Info
 ------------------------------------------------------------------------------ */
"*%%******************************************************************************\n"
"*%%	General Information\n"
"*%%******************************************************************************\n"
"*FormatVersion:		\"4.3\"\n"
"*FileVersion:		\"2.0.0\"\n"
"*PSVersion:		\"(3000.000) 100\"\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDBasicCap] : Basic Capabilities
 ------------------------------------------------------------------------------ */
"*%%******************************************************************************\n"
"*%%	Basic Capabilities\n"
"*%%******************************************************************************\n"
"*ColorDevice:		False\n"
"*DefaultColorSpace: Gray\n"
"*FileSystem:		False\n"
"*Throughput:		\"4\"\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDPageSize] : DefaultPageSize
 ------------------------------------------------------------------------------ */

"*%%******************************************************************************\n"
"*%%	Page Size\n"
"*%%******************************************************************************\n"
"*OpenUI *PageSize/Media Size: PickOne\n"
"*DefaultPageSize: %s\n"
"*PageSize Letter/US Letter:		\"\"\n"
"*PageSize Legal/US Legal:		\"\"\n"
"*PageSize A3/A3:			\"\"\n"
"*PageSize A4/A4:			\"\"\n"
"*PageSize A5/A5:			\"\"\n"
"*PageSize 110x115/11x11.5:		\"\"\n"
"*PageSize 110x120/11x12:		\"\"\n"
"*PageSize 110x170/11x17:		\"\"\n"
"*PageSize 115x110/11.5x11:		\"\"\n"
"*PageSize 115x110/11.5x11:		\"\"\n"
"*PageSize A4TF/A4 Tractor Feed:		\"\"\n"
"*CloseUI: *PageSize\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDPageRegion] : DefaultPageRegion
 ------------------------------------------------------------------------------ */

"*%%******************************************************************************\n"
"*%%	Page Region\n"
"*%%******************************************************************************\n"
"*OpenUI *PageRegion: PickOne\n"
"*DefaultPageRegion: %s\n"
"*PageRegion Letter/US Letter:		\"\"\n"
"*PageRegion Legal/US Legal:		\"\"\n"
"*PageRegion A3/A3:			\"\"\n"
"*PageRegion A4/A4:			\"\"\n"
"*PageRegion A5/A5:			\"\"\n"
"*PageRegion 110x115/11x11.5:		\"\"\n"
"*PageRegion 110x120/11x12:		\"\"\n"
"*PageRegion 110x170/11x17:		\"\"\n"
"*PageRegion 115x110/11.5x11:		\"\"\n"
"*PageRegion A4TF/A4 Tractor Feed:	\"\"\n"
"*CloseUI: *PageRegion\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDImageableArea] : DefaultImageableArea
 ------------------------------------------------------------------------------ */

"*%%******************************************************************************\n"
"*%%	Imageable Area\n"
"*%%******************************************************************************\n"
"*DefaultImageableArea: %s\n"
"*ImageableArea Letter/US Letter:	\"18.000000 36.000000 594.000000  756.000000\"\n"
"*ImageableArea Legal/US Legal:		\"18.000000 36.000000 594.000000  972.000000\"\n"
"*ImageableArea A3/A3:			\"18.000000 36.000000 823.889765 1154,551180\"\n"
"*ImageableArea A4/A4:			\"18.000000 36.000000 577.275590  805.889765\"\n"
"*ImageableArea A5/A5:			\"18.000000 36.000000 401.527560  559.275590\"\n"
"*ImageableArea 110x115/11x11.5:		\"18.000000 36.000000 774.000000  756.000000\"\n"
"*ImageableArea 110x120/11x12:		\"18.000000 36.000000 774.000000  828.000000\"\n"
"*ImageableArea 110x170/11x17:		\"18.000000 36.000000 774.000000 1188.000000\"\n"
"*ImageableArea 115x110/11.5x11:		\"18.000000 36.000000 756.000000  774.000000\"\n"
"*ImageableArea A4TF/A4 Tractor Feed:	\"18.000000 36.000000 576.000000  810.000000\"\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDPaperDimension] : DefaultPaperDimension
 ------------------------------------------------------------------------------ */

"*%%******************************************************************************\n"
"*%%	Paper Dimension\n"
"*%%******************************************************************************\n"
"*DefaultPaperDimension: %s\n"
"*PaperDimension Letter/US Letter:	\"612.000000  792.000000\"\n"
"*PaperDimension Legal/US Legal:		\"612.000000 1008.000000\"\n"
"*PaperDimension A3/A3:			\"841.889765 1190.551180\"\n"
"*PaperDimension A4/A4:			\"595.275590  841.889765\"\n"
"*PaperDimension A5/A5:			\"419.527560  595.275590\"\n"
"*PaperDimension 110x115/11x11.5:	\"792.000000  828.000000\"\n"
"*PaperDimension 110x120/11x12:		\"792.000000  864.000000\"\n"
"*PaperDimension 110x170/11x17:		\"792.000000 1224.000000\"\n"
"*PaperDimension 115x110/11.5x11:	\"828.000000  792.000000\"\n"
"*PaperDimension A4TF/A4 Tractor Feed:	\"594.000000  846.000000\"\n"
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDConstraints] : Constraints
 ------------------------------------------------------------------------------ */
"*%%******************************************************************************\n"
"*%%	Constraints\n"
"*%%******************************************************************************\n"
#ifdef USE_CONSTRAINTS
"*NonUIConstraints:	*IndexDuplex FourStitchBinding *ZFolding\n"
"*NonUIConstraints:	*ZFolding *IndexDuplex FourStitchBinding\n"
#else
"*%% No constraints\n"
#endif // USE_CONSTRAINTS
"\n",

/* ------------------------------------------------------------------------------
chunk[PPDLanguageFile1] : LanguageFile
 ------------------------------------------------------------------------------ */
#ifdef VERSION1
"*%%******************************************************************************\n"
"*%%	LanguageFile\n"
"*%%******************************************************************************\n"
"*OpenUI *LanguageFile/Language File: PickOne\n"
"*DefaultLanguageFile: american_g0.ibk\n"
"*LanguageFile NoTranslation.ibk/%s: \"\"\n"
"*LanguageFile american_g0.ibk/American Grade 0: \"\"\n"
"*LanguageFile american_g1.ibk/American Grade 1: \"\"\n"
"*LanguageFile american_g2.ibk/American Grade 2: \"\"\n"
"*LanguageFile arabic_g0.ibk/Arabic Grade 0: \"\"\n"
"*LanguageFile arabic_g0_v1.ibk/Arabic Grade 0: \"\"\n"
"*LanguageFile azeri_g1.ibk/Azeri Grade 1: \"\"\n"
"*LanguageFile bangla_g1.ibk/Bangla grade 1: \"\"\n"
"*LanguageFile belgian_g1.ibk/Belgian grade 1: \"\"\n"
"*LanguageFile brazil_g1.ibk/Brazilian grade 1: \"\"\n"
"*LanguageFile bulgarian_g1.ibk/Bulgarian Grade 1: \"\"\n"
"*LanguageFile croatian_g1.ibk/Croatian Grade 1: \"\"\n"
"*LanguageFile czech_g1.ibk/Czech Grade 1: \"\"\n",

"*LanguageFile czech_g1_v11.ibk/Czech Grade 1, v1.1: \"\"\n"
"*LanguageFile danish_g1.ibk/Danish Grade 1: \"\"\n"
"*LanguageFile dutch_g1.ibk/Dutch grade 1: \"\"\n"
"*LanguageFile english_g1.ibk/English Grade 1: \"\"\n"
"*LanguageFile english_g2.ibk/English Grade 2: \"\"\n"
"*LanguageFile estonian_g1.ibk/Estonian Grade 1: \"\"\n"
"*LanguageFile farsi_g0_v1.ibk/Farsi Grade 0, v1: \"\"\n"
"*LanguageFile farsi_g0_v2.ibk/Farsi Grade 0, v2: \"\"\n"
"*LanguageFile finnish_g1.ibk/Finnish Grade 1: \"\"\n"
"*LanguageFile french_g1.ibk/French Grade 1: \"\"\n"
"*LanguageFile french_g1_BMN_cbfr1252.ibk/French_BMN_cbfr1252 Grade 1: \"\"\n"
"*LanguageFile french_g2.ibk/French Grade 2: \"\"\n"
"*LanguageFile french_g2_BMN_cbfr1252.ibk/French_BMN_cbfr1252 Grade 2: \"\"\n"
"*%% LanguageFile german_bm.ibk/German Braille Translator: \"\"\n"
"*LanguageFile german_g01.ibk/German Grade 0 and 1: \"\"\n"
"*LanguageFile german_g1.ibk/German Grade 1: \"\"\n",

"*LanguageFile german_g2.ibk/German Grade 2: \"\"\n"
"*LanguageFile greek_g1.ibk/Greek Grade 1: \"\"\n"
"*LanguageFile hebrew_g01.ibk/Hebrew Grade 0: \"\"\n"
"*LanguageFile hungarian_g1.ibk/Hungaryan Grade 1: \"\"\n"
"*LanguageFile icelandic_g1.ibk/Icelandic Grade 1: \"\"\n"
"*LanguageFile indonesian_g1.ibk/Indonesian Grade 1: \"\"\n"
"*LanguageFile italian_g1.ibk/Italian Grade 1: \"\"\n"
"*LanguageFile latvian_g1.ibk/Latvian Grade 1: \"\"\n"
"*LanguageFile malaysian_g2.ibk/Malaysian Grade 2, v1: \"\"\n"
"*LanguageFile nigerian_g1.ibk/Nigerian Language Grade 1: \"\"\n"
"*LanguageFile norwegian_g1.ibk/Norwegian Grade 1: \"\"\n"
"*LanguageFile norwegian_oub_0f.ibk/Norwegian and Sami: \"\"\n"
"*LanguageFile polish_g1.ibk/Polish grade 1: \"\"\n"
"*LanguageFile portuguese_g1.ibk/Portuguese grade 1: \"\"\n"
"*LanguageFile portuguese_v3_g1.ibk/Portuguese grade 1 v3: \"\"\n"
"*LanguageFile portuguese_v4_g1.ibk/Portuguese grade 1 v4: \"\"\n"
"*LanguageFile portuguese_v5_g1.ibk/Portuguese grade 1 v5: \"\"\n",

"*LanguageFile romanian.ibk/Romanian Grade 1: "": \"\"\n"
"*LanguageFile russian_g1_v1.ibk/Russian Grade 1, v1: \"\"\n"
"*LanguageFile russian_g1_v2.ibk/Russian Grade 1, v2: \"\"\n"
"*LanguageFile sami_g1.ibk/Norwegian/Davvi-Sami Grade 1: \"\"\n"
"*LanguageFile sinhala_g0.ibk/Sinhala (Modified Wijesekara Keyboard): \"\"\n"
"*LanguageFile slovak_g1.ibk/Slovak Grade 1: \"\"\n"
"*LanguageFile spanish_g1.ibk/Spanish Grade 1: \"\"\n"
"*LanguageFile swahili_g1.ibk/Swahili Grade 1: \"\"\n"
"*LanguageFile swedish_g1.ibk/Swedish litterary Braille, grade 1: \"\"\n"
"*LanguageFile swedish_g2.ibk/Swedish litterary Braille, grade 2: \"\"\n"
"*LanguageFile swedish_g3.ibk/Swedish litterary Braille, grade 3 (K-75): \"\"\n"
"*LanguageFile tajik_g1.ibk/Tajik Grade 1: \"\"\n"
"*LanguageFile turkish_g1.ibk/Turkish Grade 1: \"\"\n"
"*LanguageFile turkish_g2.ibk/Turkish Grade 2: \"\"\n"
"*LanguageFile uzbek_g1.ibk/Uzbek grade 1: \"\"\n"
"*CloseUI:	*LanguageFile\n\n",
#else
"\n",
#endif
/* ------------------------------------------------------------------------------
Empty Marker
 ------------------------------------------------------------------------------ */
""
};
